[package]
name = "bool_vec"
version = "0.3.0"
edition = "2021"
license = "MIT"
description = "A crates that exposes a vector called BoolVec which allows you to store a boolean in a single bit"
repository = "https://github.com/callb4ck/bool_vec"

[dependencies]
count-macro = "0.2.2"
